/*
 * generated by Xtext 2.9.1
 */
package org.mobadsl.grammar.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;
import org.mobadsl.grammar.ide.contentassist.antlr.MobaParser;
import org.mobadsl.grammar.ide.contentassist.antlr.internal.InternalMobaLexer;

/**
 * Manual modifications go to {@link MobaWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMobaWebModule extends DefaultWebModule {

	public AbstractMobaWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalMobaLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return MobaParser.class;
	}
	
}
