/**
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.mobadsl.grammar.ui.AbstractMobaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MobaUiModule extends AbstractMobaUiModule {
  public MobaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
