/**
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class MobaQuickfixProvider extends DefaultQuickfixProvider {
}
