/*
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.mobadsl.grammar.ide.contentassist.antlr.internal.InternalMobaParser;
import org.mobadsl.grammar.services.MobaGrammarAccess;

public class MobaParser extends AbstractContentAssistParser {

	@Inject
	private MobaGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMobaParser createParser() {
		InternalMobaParser result = new InternalMobaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMobaApplicationFeatureAccess().getAlternatives(), "rule__MobaApplicationFeature__Alternatives");
					put(grammarAccess.getMobaGeneratorAccess().getAlternatives_1(), "rule__MobaGenerator__Alternatives_1");
					put(grammarAccess.getMobaDataTypeAccess().getAlternatives_2_2_0(), "rule__MobaDataType__Alternatives_2_2_0");
					put(grammarAccess.getMobaDataTypeAccess().getAlternatives_2_2_1_1(), "rule__MobaDataType__Alternatives_2_2_1_1");
					put(grammarAccess.getMobaPropertyAccess().getAlternatives_0(), "rule__MobaProperty__Alternatives_0");
					put(grammarAccess.getMobaPropertyAccess().getAlternatives_2(), "rule__MobaProperty__Alternatives_2");
					put(grammarAccess.getMobaDataAccess().getAlternatives(), "rule__MobaData__Alternatives");
					put(grammarAccess.getMobaCacheAccess().getAlternatives_2_1_0_2(), "rule__MobaCache__Alternatives_2_1_0_2");
					put(grammarAccess.getMobaCacheAccess().getAlternatives_2_1_1_2(), "rule__MobaCache__Alternatives_2_1_1_2");
					put(grammarAccess.getMobaServiceAccess().getAlternatives(), "rule__MobaService__Alternatives");
					put(grammarAccess.getMobaDtoFeatureAccess().getAlternatives(), "rule__MobaDtoFeature__Alternatives");
					put(grammarAccess.getMobaPayloadFeatureAccess().getAlternatives(), "rule__MobaPayloadFeature__Alternatives");
					put(grammarAccess.getMobaLowerBoundAccess().getAlternatives(), "rule__MobaLowerBound__Alternatives");
					put(grammarAccess.getMobaUpperBoundAccess().getAlternatives(), "rule__MobaUpperBound__Alternatives");
					put(grammarAccess.getMobaApplicationAccess().getGroup(), "rule__MobaApplication__Group__0");
					put(grammarAccess.getMobaTemplateAccess().getGroup(), "rule__MobaTemplate__Group__0");
					put(grammarAccess.getMobaGeneratorAccess().getGroup(), "rule__MobaGenerator__Group__0");
					put(grammarAccess.getMobaDataTypeAccess().getGroup(), "rule__MobaDataType__Group__0");
					put(grammarAccess.getMobaDataTypeAccess().getGroup_2_2(), "rule__MobaDataType__Group_2_2__0");
					put(grammarAccess.getMobaDataTypeAccess().getGroup_2_2_1(), "rule__MobaDataType__Group_2_2_1__0");
					put(grammarAccess.getMobaConstantAccess().getGroup(), "rule__MobaConstant__Group__0");
					put(grammarAccess.getMobaPropertiesProviderAccess().getGroup(), "rule__MobaPropertiesProvider__Group__0");
					put(grammarAccess.getMobaPropertiesProviderAccess().getGroup_2(), "rule__MobaPropertiesProvider__Group_2__0");
					put(grammarAccess.getMobaPropertyAccess().getGroup(), "rule__MobaProperty__Group__0");
					put(grammarAccess.getMobaSettingsAccess().getGroup(), "rule__MobaSettings__Group__0");
					put(grammarAccess.getMobaSettingsAccess().getGroup_2(), "rule__MobaSettings__Group_2__0");
					put(grammarAccess.getMobaCacheAccess().getGroup(), "rule__MobaCache__Group__0");
					put(grammarAccess.getMobaCacheAccess().getGroup_2(), "rule__MobaCache__Group_2__0");
					put(grammarAccess.getMobaCacheAccess().getGroup_2_1_0(), "rule__MobaCache__Group_2_1_0__0");
					put(grammarAccess.getMobaCacheAccess().getGroup_2_1_1(), "rule__MobaCache__Group_2_1_1__0");
					put(grammarAccess.getMobaDtoAccess().getGroup(), "rule__MobaDto__Group__0");
					put(grammarAccess.getMobaDtoAccess().getGroup_2_0(), "rule__MobaDto__Group_2_0__0");
					put(grammarAccess.getMobaDtoIndexAccess().getGroup(), "rule__MobaDtoIndex__Group__0");
					put(grammarAccess.getMobaDtoIndexAccess().getGroup_2(), "rule__MobaDtoIndex__Group_2__0");
					put(grammarAccess.getMobaPayloadAccess().getGroup(), "rule__MobaPayload__Group__0");
					put(grammarAccess.getMobaPayloadAccess().getGroup_2(), "rule__MobaPayload__Group_2__0");
					put(grammarAccess.getMobaQueueAccess().getGroup(), "rule__MobaQueue__Group__0");
					put(grammarAccess.getMobaQueueAccess().getGroup_2(), "rule__MobaQueue__Group_2__0");
					put(grammarAccess.getMobaRestCustomAccess().getGroup(), "rule__MobaRestCustom__Group__0");
					put(grammarAccess.getMobaRestCrudAccess().getGroup(), "rule__MobaRestCrud__Group__0");
					put(grammarAccess.getMobaDtoAttributeAccess().getGroup(), "rule__MobaDtoAttribute__Group__0");
					put(grammarAccess.getMobaDtoReferenceAccess().getGroup(), "rule__MobaDtoReference__Group__0");
					put(grammarAccess.getMobaPayloadAttributeAccess().getGroup(), "rule__MobaPayloadAttribute__Group__0");
					put(grammarAccess.getMobaPayloadAttributeAccess().getGroup_1_4(), "rule__MobaPayloadAttribute__Group_1_4__0");
					put(grammarAccess.getMobaPayloadReferenceAccess().getGroup(), "rule__MobaPayloadReference__Group__0");
					put(grammarAccess.getMobaQueueReferenceAccess().getGroup(), "rule__MobaQueueReference__Group__0");
					put(grammarAccess.getMobaMuliplicityAccess().getGroup(), "rule__MobaMuliplicity__Group__0");
					put(grammarAccess.getMobaMuliplicityAccess().getGroup_2(), "rule__MobaMuliplicity__Group_2__0");
					put(grammarAccess.getMobaApplicationAccess().getNameAssignment_1(), "rule__MobaApplication__NameAssignment_1");
					put(grammarAccess.getMobaApplicationAccess().getFeaturesAssignment_3(), "rule__MobaApplication__FeaturesAssignment_3");
					put(grammarAccess.getMobaTemplateAccess().getTemplateAssignment_1(), "rule__MobaTemplate__TemplateAssignment_1");
					put(grammarAccess.getMobaGeneratorAccess().getGeneratorStringAssignment_1_0(), "rule__MobaGenerator__GeneratorStringAssignment_1_0");
					put(grammarAccess.getMobaGeneratorAccess().getGeneratorConstAssignment_1_1(), "rule__MobaGenerator__GeneratorConstAssignment_1_1");
					put(grammarAccess.getMobaDataTypeAccess().getNameAssignment_1(), "rule__MobaDataType__NameAssignment_1");
					put(grammarAccess.getMobaDataTypeAccess().getPrimitiveAssignment_2_0(), "rule__MobaDataType__PrimitiveAssignment_2_0");
					put(grammarAccess.getMobaDataTypeAccess().getArrayAssignment_2_1(), "rule__MobaDataType__ArrayAssignment_2_1");
					put(grammarAccess.getMobaDataTypeAccess().getDateAssignment_2_2_0_0(), "rule__MobaDataType__DateAssignment_2_2_0_0");
					put(grammarAccess.getMobaDataTypeAccess().getDateAssignment_2_2_0_1(), "rule__MobaDataType__DateAssignment_2_2_0_1");
					put(grammarAccess.getMobaDataTypeAccess().getDateAssignment_2_2_0_2(), "rule__MobaDataType__DateAssignment_2_2_0_2");
					put(grammarAccess.getMobaDataTypeAccess().getDateFormatStringAssignment_2_2_1_1_0(), "rule__MobaDataType__DateFormatStringAssignment_2_2_1_1_0");
					put(grammarAccess.getMobaDataTypeAccess().getDateFormatConstantAssignment_2_2_1_1_1(), "rule__MobaDataType__DateFormatConstantAssignment_2_2_1_1_1");
					put(grammarAccess.getMobaConstantAccess().getNameAssignment_1(), "rule__MobaConstant__NameAssignment_1");
					put(grammarAccess.getMobaConstantAccess().getValueAssignment_3(), "rule__MobaConstant__ValueAssignment_3");
					put(grammarAccess.getMobaPropertiesProviderAccess().getPropertiesAssignment_1(), "rule__MobaPropertiesProvider__PropertiesAssignment_1");
					put(grammarAccess.getMobaPropertiesProviderAccess().getPropertiesAssignment_2_1(), "rule__MobaPropertiesProvider__PropertiesAssignment_2_1");
					put(grammarAccess.getMobaPropertyAccess().getKeyStringAssignment_0_0(), "rule__MobaProperty__KeyStringAssignment_0_0");
					put(grammarAccess.getMobaPropertyAccess().getKeyConstAssignment_0_1(), "rule__MobaProperty__KeyConstAssignment_0_1");
					put(grammarAccess.getMobaPropertyAccess().getValueStringAssignment_2_0(), "rule__MobaProperty__ValueStringAssignment_2_0");
					put(grammarAccess.getMobaPropertyAccess().getValueConstAssignment_2_1(), "rule__MobaProperty__ValueConstAssignment_2_1");
					put(grammarAccess.getMobaSettingsAccess().getSuperTypeAssignment_2_1(), "rule__MobaSettings__SuperTypeAssignment_2_1");
					put(grammarAccess.getMobaCacheAccess().getCacheTypeStringAssignment_2_1_0_2_0(), "rule__MobaCache__CacheTypeStringAssignment_2_1_0_2_0");
					put(grammarAccess.getMobaCacheAccess().getCacheTypeConstAssignment_2_1_0_2_1(), "rule__MobaCache__CacheTypeConstAssignment_2_1_0_2_1");
					put(grammarAccess.getMobaCacheAccess().getCacheStrategyStringAssignment_2_1_1_2_0(), "rule__MobaCache__CacheStrategyStringAssignment_2_1_1_2_0");
					put(grammarAccess.getMobaCacheAccess().getCacheStrategyConstAssignment_2_1_1_2_1(), "rule__MobaCache__CacheStrategyConstAssignment_2_1_1_2_1");
					put(grammarAccess.getMobaDtoAccess().getNameAssignment_1(), "rule__MobaDto__NameAssignment_1");
					put(grammarAccess.getMobaDtoAccess().getSuperTypeAssignment_2_0_1(), "rule__MobaDto__SuperTypeAssignment_2_0_1");
					put(grammarAccess.getMobaDtoAccess().getCacheAssignment_2_1(), "rule__MobaDto__CacheAssignment_2_1");
					put(grammarAccess.getMobaDtoAccess().getFeaturesAssignment_5(), "rule__MobaDto__FeaturesAssignment_5");
					put(grammarAccess.getMobaDtoAccess().getIndexAssignment_6(), "rule__MobaDto__IndexAssignment_6");
					put(grammarAccess.getMobaDtoIndexAccess().getAttributesAssignment_1(), "rule__MobaDtoIndex__AttributesAssignment_1");
					put(grammarAccess.getMobaDtoIndexAccess().getAttributesAssignment_2_1(), "rule__MobaDtoIndex__AttributesAssignment_2_1");
					put(grammarAccess.getMobaPayloadAccess().getNameAssignment_1(), "rule__MobaPayload__NameAssignment_1");
					put(grammarAccess.getMobaPayloadAccess().getSuperTypeAssignment_2_1(), "rule__MobaPayload__SuperTypeAssignment_2_1");
					put(grammarAccess.getMobaPayloadAccess().getFeaturesAssignment_5(), "rule__MobaPayload__FeaturesAssignment_5");
					put(grammarAccess.getMobaQueueAccess().getNameAssignment_1(), "rule__MobaQueue__NameAssignment_1");
					put(grammarAccess.getMobaQueueAccess().getSuperTypeAssignment_2_1(), "rule__MobaQueue__SuperTypeAssignment_2_1");
					put(grammarAccess.getMobaQueueAccess().getFeaturesAssignment_5(), "rule__MobaQueue__FeaturesAssignment_5");
					put(grammarAccess.getMobaRestCustomAccess().getNameAssignment_1(), "rule__MobaRestCustom__NameAssignment_1");
					put(grammarAccess.getMobaRestCrudAccess().getNameAssignment_1(), "rule__MobaRestCrud__NameAssignment_1");
					put(grammarAccess.getMobaDtoAttributeAccess().getLazyAssignment_1_0(), "rule__MobaDtoAttribute__LazyAssignment_1_0");
					put(grammarAccess.getMobaDtoAttributeAccess().getTransientAssignment_1_1(), "rule__MobaDtoAttribute__TransientAssignment_1_1");
					put(grammarAccess.getMobaDtoAttributeAccess().getDomainKeyAssignment_1_2(), "rule__MobaDtoAttribute__DomainKeyAssignment_1_2");
					put(grammarAccess.getMobaDtoAttributeAccess().getDomainDescriptionAssignment_1_3(), "rule__MobaDtoAttribute__DomainDescriptionAssignment_1_3");
					put(grammarAccess.getMobaDtoAttributeAccess().getTypeAssignment_2(), "rule__MobaDtoAttribute__TypeAssignment_2");
					put(grammarAccess.getMobaDtoAttributeAccess().getNameAssignment_4(), "rule__MobaDtoAttribute__NameAssignment_4");
					put(grammarAccess.getMobaMultiplicityProviderAccess().getMultiplicityAssignment(), "rule__MobaMultiplicityProvider__MultiplicityAssignment");
					put(grammarAccess.getMobaDtoReferenceAccess().getCascadingAssignment_1_0(), "rule__MobaDtoReference__CascadingAssignment_1_0");
					put(grammarAccess.getMobaDtoReferenceAccess().getLazyAssignment_1_1(), "rule__MobaDtoReference__LazyAssignment_1_1");
					put(grammarAccess.getMobaDtoReferenceAccess().getTransientAssignment_1_2(), "rule__MobaDtoReference__TransientAssignment_1_2");
					put(grammarAccess.getMobaDtoReferenceAccess().getTypeAssignment_2(), "rule__MobaDtoReference__TypeAssignment_2");
					put(grammarAccess.getMobaDtoReferenceAccess().getNameAssignment_4(), "rule__MobaDtoReference__NameAssignment_4");
					put(grammarAccess.getMobaPayloadAttributeAccess().getLazyAssignment_1_0(), "rule__MobaPayloadAttribute__LazyAssignment_1_0");
					put(grammarAccess.getMobaPayloadAttributeAccess().getTransientAssignment_1_1(), "rule__MobaPayloadAttribute__TransientAssignment_1_1");
					put(grammarAccess.getMobaPayloadAttributeAccess().getDomainKeyAssignment_1_2(), "rule__MobaPayloadAttribute__DomainKeyAssignment_1_2");
					put(grammarAccess.getMobaPayloadAttributeAccess().getDomainDescriptionAssignment_1_3(), "rule__MobaPayloadAttribute__DomainDescriptionAssignment_1_3");
					put(grammarAccess.getMobaPayloadAttributeAccess().getAliasAssignment_1_4_2(), "rule__MobaPayloadAttribute__AliasAssignment_1_4_2");
					put(grammarAccess.getMobaPayloadAttributeAccess().getTypeAssignment_2(), "rule__MobaPayloadAttribute__TypeAssignment_2");
					put(grammarAccess.getMobaPayloadAttributeAccess().getNameAssignment_4(), "rule__MobaPayloadAttribute__NameAssignment_4");
					put(grammarAccess.getMobaPayloadReferenceAccess().getCascadingAssignment_1_0(), "rule__MobaPayloadReference__CascadingAssignment_1_0");
					put(grammarAccess.getMobaPayloadReferenceAccess().getLazyAssignment_1_1(), "rule__MobaPayloadReference__LazyAssignment_1_1");
					put(grammarAccess.getMobaPayloadReferenceAccess().getTransientAssignment_1_2(), "rule__MobaPayloadReference__TransientAssignment_1_2");
					put(grammarAccess.getMobaPayloadReferenceAccess().getTypeAssignment_2(), "rule__MobaPayloadReference__TypeAssignment_2");
					put(grammarAccess.getMobaPayloadReferenceAccess().getNameAssignment_4(), "rule__MobaPayloadReference__NameAssignment_4");
					put(grammarAccess.getMobaQueueReferenceAccess().getCascadingAssignment_1_0(), "rule__MobaQueueReference__CascadingAssignment_1_0");
					put(grammarAccess.getMobaQueueReferenceAccess().getLazyAssignment_1_1(), "rule__MobaQueueReference__LazyAssignment_1_1");
					put(grammarAccess.getMobaQueueReferenceAccess().getTransientAssignment_1_2(), "rule__MobaQueueReference__TransientAssignment_1_2");
					put(grammarAccess.getMobaQueueReferenceAccess().getTypeAssignment_2(), "rule__MobaQueueReference__TypeAssignment_2");
					put(grammarAccess.getMobaQueueReferenceAccess().getNameAssignment_4(), "rule__MobaQueueReference__NameAssignment_4");
					put(grammarAccess.getMobaMuliplicityAccess().getLowerAssignment_1(), "rule__MobaMuliplicity__LowerAssignment_1");
					put(grammarAccess.getMobaMuliplicityAccess().getUpperAssignment_2_1(), "rule__MobaMuliplicity__UpperAssignment_2_1");
					put(grammarAccess.getMobaDataTypeAccess().getUnorderedGroup_2(), "rule__MobaDataType__UnorderedGroup_2");
					put(grammarAccess.getMobaCacheAccess().getUnorderedGroup_2_1(), "rule__MobaCache__UnorderedGroup_2_1");
					put(grammarAccess.getMobaDtoAccess().getUnorderedGroup_2(), "rule__MobaDto__UnorderedGroup_2");
					put(grammarAccess.getMobaDtoAttributeAccess().getUnorderedGroup_1(), "rule__MobaDtoAttribute__UnorderedGroup_1");
					put(grammarAccess.getMobaDtoReferenceAccess().getUnorderedGroup_1(), "rule__MobaDtoReference__UnorderedGroup_1");
					put(grammarAccess.getMobaPayloadAttributeAccess().getUnorderedGroup_1(), "rule__MobaPayloadAttribute__UnorderedGroup_1");
					put(grammarAccess.getMobaPayloadReferenceAccess().getUnorderedGroup_1(), "rule__MobaPayloadReference__UnorderedGroup_1");
					put(grammarAccess.getMobaQueueReferenceAccess().getUnorderedGroup_1(), "rule__MobaQueueReference__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalMobaParser typedParser = (InternalMobaParser) parser;
			typedParser.entryRuleMobaApplication();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MobaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MobaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
