/**
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.web;

import com.google.inject.Injector;
import java.util.List;
import java.util.concurrent.ExecutorService;
import javax.servlet.annotation.WebServlet;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
@WebServlet(name = "XtextServices", urlPatterns = "/xtext-service/*")
@SuppressWarnings("all")
public class MobaServlet /* implements XtextServlet  */{
  private final List<ExecutorService> executorServices = CollectionLiterals.<ExecutorService>newArrayList();
  
  @Override
  public Injector init() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\ninit cannot be resolved");
  }
  
  @Override
  public Object destroy() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\ndestroy cannot be resolved");
  }
}
