/*
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MobaStandaloneSetup extends MobaStandaloneSetupGenerated {

	def static void doSetup() {
		new MobaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
