/*
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMobaScopeProvider extends DelegatingScopeProvider {
}
