/**
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.mobadsl.semantic.model.moba.MobaConstant;
import org.mobadsl.semantic.model.moba.MobaDataType;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class MobaOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final MobaDataType modelElement) {
    return true;
  }
  
  public boolean _isLeaf(final MobaConstant modelElement) {
    return true;
  }
}
