/*
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MobaUiModule extends AbstractMobaUiModule {
}
