/**
 * generated by Xtext 2.9.0.beta6
 */
package org.mobadsl.grammar.generator;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import java.util.Collections;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.mobadsl.grammar.generator.ExtensionGeneratorDelegate;
import org.mobadsl.semantic.model.moba.MobaApplication;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MobaGenerator extends AbstractGenerator {
  @Inject
  private ExtensionGeneratorDelegate generatorDelegate;
  
  @Override
  public void doGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final List<String> generatorIds = this.collectGeneratorIds(input);
    this.generatorDelegate.generate(input, fsa, context, generatorIds);
  }
  
  @Override
  public void beforeGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final List<String> generatorIds = this.collectGeneratorIds(input);
    this.generatorDelegate.beforeGenerate(input, fsa, context, generatorIds);
  }
  
  @Override
  public void afterGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final List<String> generatorIds = this.collectGeneratorIds(input);
    this.generatorDelegate.afterGenerate(input, fsa, context, generatorIds);
  }
  
  public List<String> collectGeneratorIds(final Resource resource) {
    EList<EObject> _contents = resource.getContents();
    EObject _get = _contents.get(0);
    final MobaApplication application = ((MobaApplication) _get);
    boolean _equals = Objects.equal(application, null);
    if (_equals) {
      return Collections.<String>emptyList();
    }
    org.mobadsl.semantic.model.moba.MobaGenerator _activeGenerator = application.getActiveGenerator();
    List<String> _allGeneratorIds = null;
    if (_activeGenerator!=null) {
      _allGeneratorIds=_activeGenerator.getAllGeneratorIds();
    }
    return _allGeneratorIds;
  }
}
