<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moba" nsURI="http://www.mobadsl.org/model/Moba" nsPrefix="moba">
  <eClassifiers xsi:type="ecore:EClass" name="MobaApplication" eSuperTypes="#//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaApplicationFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaApplicationFeature" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaTemplate" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//MobaApplication"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="downloadTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaServer" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//MobaREST"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorization" eType="#//MobaAuthorization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaAuthorization" eSuperTypes="#//MobaApplicationFeature #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGenerator" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaGeneratorFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeneratorFeature" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeneratorMixinFeature" eSuperTypes="#//MobaGeneratorFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorRef" eType="#//MobaGenerator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeneratorIDFeature" eSuperTypes="#//MobaGeneratorFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatorId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatorVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDataType" eSuperTypes="#//MobaApplicationFeature #//MobaPropertiesAble #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormatString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dateFormatConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumAST" eType="#//MobaEnum"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstant" eSuperTypes="#//MobaApplicationFeature #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueAST" eType="#//MobaConstantValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstantValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//MobaConstantValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaPropertiesAble" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//MobaProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaData" abstract="true" eSuperTypes="#//MobaApplicationFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaSettings" eSuperTypes="#//MobaApplicationFeature #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaSettings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaSettingsFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaCache">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheTypeString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cacheTypeConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheStrategyString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cacheStrategyConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntity" eSuperTypes="#//MobaData #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cache" eType="#//MobaCache"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaEntityFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//MobaEntityIndex"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityIndex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" unique="false"
        upperBound="-1" eType="#//MobaEntityAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDto" eSuperTypes="#//MobaData #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaDto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaDtoFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaQueue" eSuperTypes="#//MobaData #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaQueue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaQueueFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaREST" abstract="true" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestDto" eType="#//MobaDto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseDto" eType="#//MobaDto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorDto" eType="#//MobaDto"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaRESTOperations">
    <eLiterals name="GET" literal="GET"/>
    <eLiterals name="PUT" value="1" literal="PUT"/>
    <eLiterals name="DELETE" value="2" literal="DELETE"/>
    <eLiterals name="POST" value="3" literal="POST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTCustomService" eSuperTypes="#//MobaREST #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//MobaRESTOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTWorkflow" eSuperTypes="#//MobaREST #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//MobaREST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTCrud" eSuperTypes="#//MobaREST #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operations" upperBound="-1"
        eType="#//MobaRESTOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaFeature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityFeature" abstract="true" eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityAttribute" eSuperTypes="#//MobaEntityFeature #//MobaMultiplicityAble #//MobaPropertiesAble #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMultiplicityAble" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//MobaMuliplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityReference" eSuperTypes="#//MobaEntityFeature #//MobaMultiplicityAble #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDtoFeature" abstract="true" eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDtoAttribute" eSuperTypes="#//MobaDtoFeature #//MobaMultiplicityAble #//MobaPropertiesAble #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDtoReference" eSuperTypes="#//MobaDtoFeature #//MobaMultiplicityAble #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDto"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaQueueFeature" abstract="true" eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaQueueReference" eSuperTypes="#//MobaQueueFeature #//MobaMultiplicityAble #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMuliplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="#//MobaLowerBound"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="#//MobaUpperBound"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaLowerBound">
    <eLiterals name="OPTIONAL" literal="?"/>
    <eLiterals name="MANY" value="1" literal="*"/>
    <eLiterals name="ZERO" value="2" literal="0"/>
    <eLiterals name="ATLEASTONE" value="3" literal="+"/>
    <eLiterals name="ONE" value="4" literal="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaUpperBound">
    <eLiterals name="NULL" literal="NULL"/>
    <eLiterals name="ONE" value="1" literal="1"/>
    <eLiterals name="MANY" value="2" literal="*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaSettingsFeature" abstract="true"
      eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaSettingsAttribute" eSuperTypes="#//MobaSettingsFeature #//MobaMultiplicityAble #//MobaPropertiesAble #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstraintable" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//MobaConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRegexpConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMinConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMaxConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaFutureConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaPastConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaNotNullConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaNullConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMinLengthConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMaxLengthConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDigitsConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterIntegerValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterIntegerConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterFractionValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterFractionConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEnum" eSuperTypes="#//MobaApplicationFeature #//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaEnum"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//MobaEnumLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eSubpackages name="index" nsURI="http://www.mobadsl.org/template/repository/Index"
      nsPrefix="index">
    <eClassifiers xsi:type="ecore:EClass" name="MobaIndex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
          eType="#//index/MobaIndexEntry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MobaIndexEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePath" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateDescription"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateVersion" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transientTemplate" eType="#//MobaApplication"
          transient="true" derived="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
