<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moba" nsURI="http://www.mobadsl.org/model/Moba" nsPrefix="moba">
  <eClassifiers xsi:type="ecore:EClass" name="MobaModel" eSuperTypes="#//MobaFriendsAble">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaModelFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaModelFeature" abstract="true" eSuperTypes="#//MobaFriendsAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaProject" eSuperTypes="#//MobaModelFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiApplication" eType="#//MobaApplication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundApplication"
        eType="#//MobaApplication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaApplication" eSuperTypes="#//MobaModelFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaApplicationFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaApplicationFeature" abstract="true"
      eSuperTypes="#//MobaFriendsAble"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaTemplate" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//MobaApplication"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="downloadTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaServer" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="urlConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaServer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//MobaREST"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorization" upperBound="-1"
        eType="#//MobaAuthorization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaAuthorization" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaTransportSerializationType" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGenerator" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaGeneratorFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeneratorFeature" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeneratorMixinFeature" eSuperTypes="#//MobaGeneratorFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorRef" eType="#//MobaGenerator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeneratorIDFeature" eSuperTypes="#//MobaGeneratorFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatorId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatorVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeneratorSlot" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaGeneratorSlot"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDataType" eSuperTypes="#//MobaApplicationFeature #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumAST" eType="#//MobaEnum"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormatString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dateFormatConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstant" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueAST" eType="#//MobaConstantValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstantValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueConstFunctions" upperBound="-1"
        eType="#//MobaConstantValueFunction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueConstToLowerCase"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//MobaConstantValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaConstantValueFunction">
    <eLiterals name="TO_LOWER_CASE" literal="TO_LOWER_CASE"/>
    <eLiterals name="TO_UPPER_CASE" value="1" literal="TO_UPPER_CASE"/>
    <eLiterals name="TO_FIRST_UPPER_CASE" value="2" literal="TO_FIRST_UPPER_CASE"/>
    <eLiterals name="TO_FIRST_LOWER_CASE" value="3" literal="TO_FIRST_LOWER_CASE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaPropertiesAble" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//MobaProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaData" abstract="true" eSuperTypes="#//MobaApplicationFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaSettings" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaSettings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaSettingsFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaCache">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheTypeString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cacheTypeConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheStrategyString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cacheStrategyConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntity" eSuperTypes="#//MobaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cache" eType="#//MobaCache"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaEntityFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indizes" upperBound="-1"
        eType="#//MobaEntityIndex" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityIndex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" unique="false"
        upperBound="-1" eType="#//MobaEntityAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDto" eSuperTypes="#//MobaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaDto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaDtoFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serializationType" eType="#//MobaTransportSerializationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaQueue" eSuperTypes="#//MobaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaQueue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//MobaQueueFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaREST" abstract="true" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestDto" eType="#//MobaRESTPayloadDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseDto" eType="#//MobaRESTPayloadDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorDto" eType="#//MobaRESTPayloadDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//MobaRESTAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTPayloadDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dto" eType="#//MobaDto"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serializationType" eType="#//MobaTransportSerializationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaRESTMethods">
    <eLiterals name="GET" literal="GET"/>
    <eLiterals name="PUT" value="1" literal="PUT"/>
    <eLiterals name="DELETE" value="2" literal="DELETE"/>
    <eLiterals name="POST" value="3" literal="POST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTCustomService" eSuperTypes="#//MobaREST">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//MobaRESTMethods"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//MobaRESTAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaRESTCustomService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTWorkflow" eSuperTypes="#//MobaREST">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//MobaREST"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaRESTWorkflow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRESTCrud" eSuperTypes="#//MobaREST">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operations" upperBound="-1"
        eType="#//MobaRESTMethods"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaRESTCrud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaFeature" abstract="true" eSuperTypes="#//MobaFriendsAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityFeature" abstract="true" eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityAttribute" eSuperTypes="#//MobaEntityFeature #//MobaMultiplicityAble #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMultiplicityAble" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//MobaMuliplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityReference" eSuperTypes="#//MobaEntityFeature #//MobaMultiplicityAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//MobaEntityReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEntityEmbeddable" eSuperTypes="#//MobaEntityFeature #//MobaMultiplicityAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDtoFeature" abstract="true" eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDtoAttribute" eSuperTypes="#//MobaDtoFeature #//MobaMultiplicityAble #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDtoReference" eSuperTypes="#//MobaDtoFeature #//MobaMultiplicityAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//MobaDtoReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDtoEmbeddable" eSuperTypes="#//MobaDtoFeature #//MobaMultiplicityAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDto"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaQueueFeature" abstract="true" eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaQueueReference" eSuperTypes="#//MobaQueueFeature #//MobaMultiplicityAble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMuliplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="#//MobaLowerBound"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="#//MobaUpperBound"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaLowerBound">
    <eLiterals name="OPTIONAL" literal="?"/>
    <eLiterals name="MANY" value="1" literal="*"/>
    <eLiterals name="ZERO" value="2" literal="0"/>
    <eLiterals name="ATLEASTONE" value="3" literal="+"/>
    <eLiterals name="ONE" value="4" literal="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaUpperBound">
    <eLiterals name="NULL" literal="NULL"/>
    <eLiterals name="ONE" value="1" literal="1"/>
    <eLiterals name="MANY" value="2" literal="*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaSettingsFeature" abstract="true"
      eSuperTypes="#//MobaFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaSettingsAttribute" eSuperTypes="#//MobaSettingsFeature #//MobaMultiplicityAble #//MobaConstraintable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MobaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstraintable" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//MobaConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaConstraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaRegexpConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMinConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMaxConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaFutureConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaPastConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaNotNullConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaNullConstraint" eSuperTypes="#//MobaConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMinLengthConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaMaxLengthConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDigitsConstraint" eSuperTypes="#//MobaConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterIntegerValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterIntegerConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterFractionValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterFractionConst" eType="#//MobaConstant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEnum" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//MobaEnumLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaTrigger" abstract="true" eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaTrigger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaAppInstallTrigger" eSuperTypes="#//MobaTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaAppUpdateTrigger" eSuperTypes="#//MobaTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaSMSTrigger" eSuperTypes="#//MobaTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaDeviceStartupTrigger" eSuperTypes="#//MobaTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaEmailTrigger" eSuperTypes="#//MobaTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaTimerTrigger" eSuperTypes="#//MobaTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaPushTrigger" eSuperTypes="#//MobaTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobaGeofenceTrigger" eSuperTypes="#//MobaTrigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" eType="#//MobaGeofenceEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaGeofenceEvent">
    <eLiterals name="ENTER" literal="ENTER"/>
    <eLiterals name="LEAVE" value="1" literal="LEAVE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaFriend">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueConst" eType="#//MobaConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaFriendsAble" abstract="true" eSuperTypes="#//MobaPropertiesAble">
    <eStructuralFeatures xsi:type="ecore:EReference" name="friends" upperBound="-1"
        eType="#//MobaFriend" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaExternalModule" abstract="true"
      eSuperTypes="#//MobaApplicationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//MobaExternalModule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaBluetoothModule" eSuperTypes="#//MobaExternalModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MobaBlueToothModuleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaNFCModule" eSuperTypes="#//MobaExternalModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MobaNFCModuleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MobaPushModule" eSuperTypes="#//MobaExternalModule"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaNFCModuleType">
    <eLiterals name="ID" literal="ID"/>
    <eLiterals name="CUSTOM" value="1" literal="CUSTOM"/>
    <eLiterals name="TEXT" value="2" literal="TEXT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobaBlueToothModuleType">
    <eLiterals name="LE" literal="LE"/>
    <eLiterals name="SPP" value="1" literal="SPP"/>
    <eLiterals name="BEACON" value="2" literal="BEACON"/>
  </eClassifiers>
  <eSubpackages name="index" nsURI="http://www.mobadsl.org/template/repository/Index"
      nsPrefix="index">
    <eClassifiers xsi:type="ecore:EClass" name="MobaIndex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
          eType="#//index/MobaIndexEntry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MobaIndexEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePath" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateDescription"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateVersion" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transientTemplate" eType="#//MobaApplication"
          transient="true" derived="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
